### PR TITLE
Update CI to tag repo.

### PR DESCRIPTION
**Pull request by kierans**
This is based on what we did for https://github.com/w-pay/sdk-wpay-js

### CODE REVIEW

**Review by NedaRobatMeily — APPROVED** [review]

**Review by applimatix — APPROVED** [review]

**Comment by kierans** [comment]
@applimatix 

Before we merge this we need to answer
1. If we want to change the groupId can JitPack handle this.
2. If we want to restart versioning can JitPack handle this.

Based on my reading of the docs, the "group" of the artefact is the repo itself. Subsequently when we mode to "WPay 2" we may need to create a brand new repo and deprecate this one in order to "start again" with JitPack.

Can you see another alternative?

**Comment by applimatix** [comment]
@kierans 

1. I think we could by adding the DNS TEXT record. Currently we have - 
groupid = com.github.w-pay (Add DNS TEXT record to change this)
projectid = sdk-wpay-android (change repo name to change this)

2. We would need to reset the tags and remove the artefacts, we could move the old tags using tag folders so change the tags to wpay1.0/v4.4.2 which would have a resultant version of wpay1.0~v4.4.2

**Comment by kierans** [comment]
I think we can merge this.

**Comment by kierans** [comment]
For #5

**Pull request merged**
